// Automatically generated by odin 1.5.4 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
typedef struct deterministic_internal {
  double *age_rate;
  double *ageing_M;
  double *ageing_R;
  double *ageing_S;
  double *ageing_V;
  double birth_rate;
  double *child_bearing_ages;
  double *death_rate;
  double *deaths_M;
  double *deaths_R;
  double *deaths_S;
  double *deaths_V;
  int dim_age_rate;
  int dim_ageing_M;
  int dim_ageing_R;
  int dim_ageing_S;
  int dim_ageing_V;
  int dim_child_bearing_ages;
  int dim_death_rate;
  int dim_deaths_M;
  int dim_deaths_R;
  int dim_deaths_S;
  int dim_deaths_V;
  int dim_foi;
  int dim_infections;
  int dim_M;
  int dim_M_0;
  int dim_M_child_bearing;
  int dim_natural_waning;
  int dim_R;
  int dim_R_0;
  int dim_S;
  int dim_S_0;
  int dim_S_child_bearing;
  int dim_total_vaccine_doses;
  int dim_V;
  int dim_vaccination_attempts;
  int dim_vaccination_doses;
  int dim_vaccination_rate;
  int dim_vaccinations;
  int dim_vaccine_waning;
  double *foi;
  double *infections;
  double *initial_M;
  double *initial_R;
  double *initial_S;
  double *initial_V;
  double *M_0;
  double *M_child_bearing;
  double maternal_waning;
  int n_age;
  double *natural_waning;
  int offset_variable_M;
  int offset_variable_V;
  double *R_0;
  double *S_0;
  double *S_child_bearing;
  double *total_vaccine_doses;
  double *vaccination_attempts;
  double *vaccination_rate;
  double *vaccinations;
  double vaccine_efficacy;
  double *vaccine_waning;
  double waning;
} deterministic_internal;
deterministic_internal* deterministic_get_internal(SEXP internal_p, int closed_error);
static void deterministic_finalise(SEXP internal_p);
SEXP deterministic_create(SEXP user);
void deterministic_initmod_desolve(void(* odeparms) (int *, double *));
SEXP deterministic_contents(SEXP internal_p);
SEXP deterministic_set_user(SEXP internal_p, SEXP user);
SEXP deterministic_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP deterministic_use_dde_ptr);
SEXP deterministic_metadata(SEXP internal_p);
SEXP deterministic_initial_conditions(SEXP internal_p, SEXP t_ptr);
void deterministic_rhs(deterministic_internal* internal, double t, double * state, double * dstatedt, double * output);
void deterministic_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal);
void deterministic_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np);
void deterministic_output_dde(size_t n_eq, double t, double * state, size_t n_output, double * output, void * internal_p);
SEXP deterministic_rhs_r(SEXP internal_p, SEXP t, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
double scalar_real(SEXP x, const char * name);
double odin_sum1(double *x, size_t from, size_t to);
deterministic_internal* deterministic_get_internal(SEXP internal_p, int closed_error) {
  deterministic_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (deterministic_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void deterministic_finalise(SEXP internal_p) {
  deterministic_internal *internal = deterministic_get_internal(internal_p, 0);
  if (internal_p) {
    R_Free(internal->age_rate);
    R_Free(internal->ageing_M);
    R_Free(internal->ageing_R);
    R_Free(internal->ageing_S);
    R_Free(internal->ageing_V);
    R_Free(internal->child_bearing_ages);
    R_Free(internal->death_rate);
    R_Free(internal->deaths_M);
    R_Free(internal->deaths_R);
    R_Free(internal->deaths_S);
    R_Free(internal->deaths_V);
    R_Free(internal->foi);
    R_Free(internal->infections);
    R_Free(internal->initial_M);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->initial_V);
    R_Free(internal->M_0);
    R_Free(internal->M_child_bearing);
    R_Free(internal->natural_waning);
    R_Free(internal->R_0);
    R_Free(internal->S_0);
    R_Free(internal->S_child_bearing);
    R_Free(internal->total_vaccine_doses);
    R_Free(internal->vaccination_attempts);
    R_Free(internal->vaccination_rate);
    R_Free(internal->vaccinations);
    R_Free(internal->vaccine_waning);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP deterministic_create(SEXP user) {
  deterministic_internal *internal = (deterministic_internal*) R_Calloc(1, deterministic_internal);
  internal->age_rate = NULL;
  internal->ageing_M = NULL;
  internal->ageing_R = NULL;
  internal->ageing_S = NULL;
  internal->ageing_V = NULL;
  internal->child_bearing_ages = NULL;
  internal->death_rate = NULL;
  internal->deaths_M = NULL;
  internal->deaths_R = NULL;
  internal->deaths_S = NULL;
  internal->deaths_V = NULL;
  internal->foi = NULL;
  internal->infections = NULL;
  internal->initial_M = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->initial_V = NULL;
  internal->M_0 = NULL;
  internal->M_child_bearing = NULL;
  internal->natural_waning = NULL;
  internal->R_0 = NULL;
  internal->S_0 = NULL;
  internal->S_child_bearing = NULL;
  internal->total_vaccine_doses = NULL;
  internal->vaccination_attempts = NULL;
  internal->vaccination_rate = NULL;
  internal->vaccinations = NULL;
  internal->vaccine_waning = NULL;
  internal->dim_ageing_M = 2;
  internal->dim_deaths_M = 2;
  internal->dim_M = 2;
  internal->dim_M_0 = 2;
  R_Free(internal->ageing_M);
  internal->ageing_M = (double*) R_Calloc(internal->dim_ageing_M, double);
  R_Free(internal->deaths_M);
  internal->deaths_M = (double*) R_Calloc(internal->dim_deaths_M, double);
  R_Free(internal->initial_M);
  internal->initial_M = (double*) R_Calloc(internal->dim_M, double);
  internal->age_rate = NULL;
  internal->birth_rate = NA_REAL;
  internal->child_bearing_ages = NULL;
  internal->death_rate = NULL;
  internal->foi = NULL;
  internal->M_0 = NULL;
  internal->maternal_waning = NA_REAL;
  internal->n_age = NA_INTEGER;
  internal->R_0 = NULL;
  internal->S_0 = NULL;
  internal->vaccination_rate = NULL;
  internal->vaccine_efficacy = NA_REAL;
  internal->waning = NA_REAL;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, deterministic_finalise);
  UNPROTECT(1);
  return ptr;
}
static deterministic_internal *deterministic_internal_ds;
void deterministic_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  deterministic_internal_ds = deterministic_get_internal(get_desolve_gparms(), 1);
}
SEXP deterministic_contents(SEXP internal_p) {
  deterministic_internal *internal = deterministic_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 64));
  SEXP age_rate = PROTECT(allocVector(REALSXP, internal->dim_age_rate));
  memcpy(REAL(age_rate), internal->age_rate, internal->dim_age_rate * sizeof(double));
  SET_VECTOR_ELT(contents, 0, age_rate);
  SEXP ageing_M = PROTECT(allocVector(REALSXP, internal->dim_ageing_M));
  memcpy(REAL(ageing_M), internal->ageing_M, internal->dim_ageing_M * sizeof(double));
  SET_VECTOR_ELT(contents, 1, ageing_M);
  SEXP ageing_R = PROTECT(allocVector(REALSXP, internal->dim_ageing_R));
  memcpy(REAL(ageing_R), internal->ageing_R, internal->dim_ageing_R * sizeof(double));
  SET_VECTOR_ELT(contents, 2, ageing_R);
  SEXP ageing_S = PROTECT(allocVector(REALSXP, internal->dim_ageing_S));
  memcpy(REAL(ageing_S), internal->ageing_S, internal->dim_ageing_S * sizeof(double));
  SET_VECTOR_ELT(contents, 3, ageing_S);
  SEXP ageing_V = PROTECT(allocVector(REALSXP, internal->dim_ageing_V));
  memcpy(REAL(ageing_V), internal->ageing_V, internal->dim_ageing_V * sizeof(double));
  SET_VECTOR_ELT(contents, 4, ageing_V);
  SET_VECTOR_ELT(contents, 5, ScalarReal(internal->birth_rate));
  SEXP child_bearing_ages = PROTECT(allocVector(REALSXP, internal->dim_child_bearing_ages));
  memcpy(REAL(child_bearing_ages), internal->child_bearing_ages, internal->dim_child_bearing_ages * sizeof(double));
  SET_VECTOR_ELT(contents, 6, child_bearing_ages);
  SEXP death_rate = PROTECT(allocVector(REALSXP, internal->dim_death_rate));
  memcpy(REAL(death_rate), internal->death_rate, internal->dim_death_rate * sizeof(double));
  SET_VECTOR_ELT(contents, 7, death_rate);
  SEXP deaths_M = PROTECT(allocVector(REALSXP, internal->dim_deaths_M));
  memcpy(REAL(deaths_M), internal->deaths_M, internal->dim_deaths_M * sizeof(double));
  SET_VECTOR_ELT(contents, 8, deaths_M);
  SEXP deaths_R = PROTECT(allocVector(REALSXP, internal->dim_deaths_R));
  memcpy(REAL(deaths_R), internal->deaths_R, internal->dim_deaths_R * sizeof(double));
  SET_VECTOR_ELT(contents, 9, deaths_R);
  SEXP deaths_S = PROTECT(allocVector(REALSXP, internal->dim_deaths_S));
  memcpy(REAL(deaths_S), internal->deaths_S, internal->dim_deaths_S * sizeof(double));
  SET_VECTOR_ELT(contents, 10, deaths_S);
  SEXP deaths_V = PROTECT(allocVector(REALSXP, internal->dim_deaths_V));
  memcpy(REAL(deaths_V), internal->deaths_V, internal->dim_deaths_V * sizeof(double));
  SET_VECTOR_ELT(contents, 11, deaths_V);
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_age_rate));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_ageing_M));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_ageing_R));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_ageing_S));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_ageing_V));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_child_bearing_ages));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_death_rate));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_deaths_M));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_deaths_R));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_deaths_S));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_deaths_V));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_foi));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_infections));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_M));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_M_0));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_M_child_bearing));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_natural_waning));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_R_0));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_S_0));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_S_child_bearing));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_total_vaccine_doses));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_V));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->dim_vaccination_attempts));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->dim_vaccination_doses));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->dim_vaccination_rate));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->dim_vaccinations));
  SET_VECTOR_ELT(contents, 40, ScalarInteger(internal->dim_vaccine_waning));
  SEXP foi = PROTECT(allocVector(REALSXP, internal->dim_foi));
  memcpy(REAL(foi), internal->foi, internal->dim_foi * sizeof(double));
  SET_VECTOR_ELT(contents, 41, foi);
  SEXP infections = PROTECT(allocVector(REALSXP, internal->dim_infections));
  memcpy(REAL(infections), internal->infections, internal->dim_infections * sizeof(double));
  SET_VECTOR_ELT(contents, 42, infections);
  SEXP initial_M = PROTECT(allocVector(REALSXP, internal->dim_M));
  memcpy(REAL(initial_M), internal->initial_M, internal->dim_M * sizeof(double));
  SET_VECTOR_ELT(contents, 43, initial_M);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 44, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 45, initial_S);
  SEXP initial_V = PROTECT(allocVector(REALSXP, internal->dim_V));
  memcpy(REAL(initial_V), internal->initial_V, internal->dim_V * sizeof(double));
  SET_VECTOR_ELT(contents, 46, initial_V);
  SEXP M_0 = PROTECT(allocVector(REALSXP, internal->dim_M_0));
  memcpy(REAL(M_0), internal->M_0, internal->dim_M_0 * sizeof(double));
  SET_VECTOR_ELT(contents, 47, M_0);
  SEXP M_child_bearing = PROTECT(allocVector(REALSXP, internal->dim_M_child_bearing));
  memcpy(REAL(M_child_bearing), internal->M_child_bearing, internal->dim_M_child_bearing * sizeof(double));
  SET_VECTOR_ELT(contents, 48, M_child_bearing);
  SET_VECTOR_ELT(contents, 49, ScalarReal(internal->maternal_waning));
  SET_VECTOR_ELT(contents, 50, ScalarInteger(internal->n_age));
  SEXP natural_waning = PROTECT(allocVector(REALSXP, internal->dim_natural_waning));
  memcpy(REAL(natural_waning), internal->natural_waning, internal->dim_natural_waning * sizeof(double));
  SET_VECTOR_ELT(contents, 51, natural_waning);
  SET_VECTOR_ELT(contents, 52, ScalarInteger(internal->offset_variable_M));
  SET_VECTOR_ELT(contents, 53, ScalarInteger(internal->offset_variable_V));
  SEXP R_0 = PROTECT(allocVector(REALSXP, internal->dim_R_0));
  memcpy(REAL(R_0), internal->R_0, internal->dim_R_0 * sizeof(double));
  SET_VECTOR_ELT(contents, 54, R_0);
  SEXP S_0 = PROTECT(allocVector(REALSXP, internal->dim_S_0));
  memcpy(REAL(S_0), internal->S_0, internal->dim_S_0 * sizeof(double));
  SET_VECTOR_ELT(contents, 55, S_0);
  SEXP S_child_bearing = PROTECT(allocVector(REALSXP, internal->dim_S_child_bearing));
  memcpy(REAL(S_child_bearing), internal->S_child_bearing, internal->dim_S_child_bearing * sizeof(double));
  SET_VECTOR_ELT(contents, 56, S_child_bearing);
  SEXP total_vaccine_doses = PROTECT(allocVector(REALSXP, internal->dim_total_vaccine_doses));
  memcpy(REAL(total_vaccine_doses), internal->total_vaccine_doses, internal->dim_total_vaccine_doses * sizeof(double));
  SET_VECTOR_ELT(contents, 57, total_vaccine_doses);
  SEXP vaccination_attempts = PROTECT(allocVector(REALSXP, internal->dim_vaccination_attempts));
  memcpy(REAL(vaccination_attempts), internal->vaccination_attempts, internal->dim_vaccination_attempts * sizeof(double));
  SET_VECTOR_ELT(contents, 58, vaccination_attempts);
  SEXP vaccination_rate = PROTECT(allocVector(REALSXP, internal->dim_vaccination_rate));
  memcpy(REAL(vaccination_rate), internal->vaccination_rate, internal->dim_vaccination_rate * sizeof(double));
  SET_VECTOR_ELT(contents, 59, vaccination_rate);
  SEXP vaccinations = PROTECT(allocVector(REALSXP, internal->dim_vaccinations));
  memcpy(REAL(vaccinations), internal->vaccinations, internal->dim_vaccinations * sizeof(double));
  SET_VECTOR_ELT(contents, 60, vaccinations);
  SET_VECTOR_ELT(contents, 61, ScalarReal(internal->vaccine_efficacy));
  SEXP vaccine_waning = PROTECT(allocVector(REALSXP, internal->dim_vaccine_waning));
  memcpy(REAL(vaccine_waning), internal->vaccine_waning, internal->dim_vaccine_waning * sizeof(double));
  SET_VECTOR_ELT(contents, 62, vaccine_waning);
  SET_VECTOR_ELT(contents, 63, ScalarReal(internal->waning));
  SEXP nms = PROTECT(allocVector(STRSXP, 64));
  SET_STRING_ELT(nms, 0, mkChar("age_rate"));
  SET_STRING_ELT(nms, 1, mkChar("ageing_M"));
  SET_STRING_ELT(nms, 2, mkChar("ageing_R"));
  SET_STRING_ELT(nms, 3, mkChar("ageing_S"));
  SET_STRING_ELT(nms, 4, mkChar("ageing_V"));
  SET_STRING_ELT(nms, 5, mkChar("birth_rate"));
  SET_STRING_ELT(nms, 6, mkChar("child_bearing_ages"));
  SET_STRING_ELT(nms, 7, mkChar("death_rate"));
  SET_STRING_ELT(nms, 8, mkChar("deaths_M"));
  SET_STRING_ELT(nms, 9, mkChar("deaths_R"));
  SET_STRING_ELT(nms, 10, mkChar("deaths_S"));
  SET_STRING_ELT(nms, 11, mkChar("deaths_V"));
  SET_STRING_ELT(nms, 12, mkChar("dim_age_rate"));
  SET_STRING_ELT(nms, 13, mkChar("dim_ageing_M"));
  SET_STRING_ELT(nms, 14, mkChar("dim_ageing_R"));
  SET_STRING_ELT(nms, 15, mkChar("dim_ageing_S"));
  SET_STRING_ELT(nms, 16, mkChar("dim_ageing_V"));
  SET_STRING_ELT(nms, 17, mkChar("dim_child_bearing_ages"));
  SET_STRING_ELT(nms, 18, mkChar("dim_death_rate"));
  SET_STRING_ELT(nms, 19, mkChar("dim_deaths_M"));
  SET_STRING_ELT(nms, 20, mkChar("dim_deaths_R"));
  SET_STRING_ELT(nms, 21, mkChar("dim_deaths_S"));
  SET_STRING_ELT(nms, 22, mkChar("dim_deaths_V"));
  SET_STRING_ELT(nms, 23, mkChar("dim_foi"));
  SET_STRING_ELT(nms, 24, mkChar("dim_infections"));
  SET_STRING_ELT(nms, 25, mkChar("dim_M"));
  SET_STRING_ELT(nms, 26, mkChar("dim_M_0"));
  SET_STRING_ELT(nms, 27, mkChar("dim_M_child_bearing"));
  SET_STRING_ELT(nms, 28, mkChar("dim_natural_waning"));
  SET_STRING_ELT(nms, 29, mkChar("dim_R"));
  SET_STRING_ELT(nms, 30, mkChar("dim_R_0"));
  SET_STRING_ELT(nms, 31, mkChar("dim_S"));
  SET_STRING_ELT(nms, 32, mkChar("dim_S_0"));
  SET_STRING_ELT(nms, 33, mkChar("dim_S_child_bearing"));
  SET_STRING_ELT(nms, 34, mkChar("dim_total_vaccine_doses"));
  SET_STRING_ELT(nms, 35, mkChar("dim_V"));
  SET_STRING_ELT(nms, 36, mkChar("dim_vaccination_attempts"));
  SET_STRING_ELT(nms, 37, mkChar("dim_vaccination_doses"));
  SET_STRING_ELT(nms, 38, mkChar("dim_vaccination_rate"));
  SET_STRING_ELT(nms, 39, mkChar("dim_vaccinations"));
  SET_STRING_ELT(nms, 40, mkChar("dim_vaccine_waning"));
  SET_STRING_ELT(nms, 41, mkChar("foi"));
  SET_STRING_ELT(nms, 42, mkChar("infections"));
  SET_STRING_ELT(nms, 43, mkChar("initial_M"));
  SET_STRING_ELT(nms, 44, mkChar("initial_R"));
  SET_STRING_ELT(nms, 45, mkChar("initial_S"));
  SET_STRING_ELT(nms, 46, mkChar("initial_V"));
  SET_STRING_ELT(nms, 47, mkChar("M_0"));
  SET_STRING_ELT(nms, 48, mkChar("M_child_bearing"));
  SET_STRING_ELT(nms, 49, mkChar("maternal_waning"));
  SET_STRING_ELT(nms, 50, mkChar("n_age"));
  SET_STRING_ELT(nms, 51, mkChar("natural_waning"));
  SET_STRING_ELT(nms, 52, mkChar("offset_variable_M"));
  SET_STRING_ELT(nms, 53, mkChar("offset_variable_V"));
  SET_STRING_ELT(nms, 54, mkChar("R_0"));
  SET_STRING_ELT(nms, 55, mkChar("S_0"));
  SET_STRING_ELT(nms, 56, mkChar("S_child_bearing"));
  SET_STRING_ELT(nms, 57, mkChar("total_vaccine_doses"));
  SET_STRING_ELT(nms, 58, mkChar("vaccination_attempts"));
  SET_STRING_ELT(nms, 59, mkChar("vaccination_rate"));
  SET_STRING_ELT(nms, 60, mkChar("vaccinations"));
  SET_STRING_ELT(nms, 61, mkChar("vaccine_efficacy"));
  SET_STRING_ELT(nms, 62, mkChar("vaccine_waning"));
  SET_STRING_ELT(nms, 63, mkChar("waning"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(30);
  return contents;
}
SEXP deterministic_set_user(SEXP internal_p, SEXP user) {
  deterministic_internal *internal = deterministic_get_internal(internal_p, 1);
  internal->birth_rate = user_get_scalar_double(user, "birth_rate", internal->birth_rate, NA_REAL, NA_REAL);
  internal->maternal_waning = user_get_scalar_double(user, "maternal_waning", internal->maternal_waning, NA_REAL, NA_REAL);
  internal->n_age = user_get_scalar_int(user, "n_age", internal->n_age, NA_REAL, NA_REAL);
  internal->vaccine_efficacy = user_get_scalar_double(user, "vaccine_efficacy", internal->vaccine_efficacy, NA_REAL, NA_REAL);
  internal->waning = user_get_scalar_double(user, "waning", internal->waning, NA_REAL, NA_REAL);
  internal->dim_age_rate = internal->n_age;
  internal->dim_ageing_R = internal->n_age;
  internal->dim_ageing_S = internal->n_age;
  internal->dim_ageing_V = internal->n_age;
  internal->dim_child_bearing_ages = internal->n_age;
  internal->dim_death_rate = internal->n_age;
  internal->dim_deaths_R = internal->n_age;
  internal->dim_deaths_S = internal->n_age;
  internal->dim_deaths_V = internal->n_age;
  internal->dim_foi = internal->n_age;
  internal->dim_infections = internal->n_age;
  internal->dim_M_child_bearing = internal->n_age;
  internal->dim_natural_waning = internal->n_age;
  internal->dim_R = internal->n_age;
  internal->dim_R_0 = internal->n_age;
  internal->dim_S = internal->n_age;
  internal->dim_S_0 = internal->n_age;
  internal->dim_S_child_bearing = internal->n_age;
  internal->dim_total_vaccine_doses = internal->n_age;
  internal->dim_V = internal->n_age;
  internal->dim_vaccination_attempts = internal->n_age;
  internal->dim_vaccination_doses = internal->n_age;
  internal->dim_vaccination_rate = internal->n_age;
  internal->dim_vaccinations = internal->n_age;
  internal->dim_vaccine_waning = internal->n_age;
  internal->M_0 = (double*) user_get_array(user, false, internal->M_0, "M_0", NA_REAL, NA_REAL, 1, internal->dim_M_0);
  internal->age_rate = (double*) user_get_array(user, false, internal->age_rate, "age_rate", NA_REAL, NA_REAL, 1, internal->dim_age_rate);
  R_Free(internal->ageing_R);
  internal->ageing_R = (double*) R_Calloc(internal->dim_ageing_R, double);
  R_Free(internal->ageing_S);
  internal->ageing_S = (double*) R_Calloc(internal->dim_ageing_S, double);
  R_Free(internal->ageing_V);
  internal->ageing_V = (double*) R_Calloc(internal->dim_ageing_V, double);
  R_Free(internal->deaths_R);
  internal->deaths_R = (double*) R_Calloc(internal->dim_deaths_R, double);
  R_Free(internal->deaths_S);
  internal->deaths_S = (double*) R_Calloc(internal->dim_deaths_S, double);
  R_Free(internal->deaths_V);
  internal->deaths_V = (double*) R_Calloc(internal->dim_deaths_V, double);
  R_Free(internal->infections);
  internal->infections = (double*) R_Calloc(internal->dim_infections, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->initial_V);
  internal->initial_V = (double*) R_Calloc(internal->dim_V, double);
  R_Free(internal->M_child_bearing);
  internal->M_child_bearing = (double*) R_Calloc(internal->dim_M_child_bearing, double);
  R_Free(internal->natural_waning);
  internal->natural_waning = (double*) R_Calloc(internal->dim_natural_waning, double);
  R_Free(internal->S_child_bearing);
  internal->S_child_bearing = (double*) R_Calloc(internal->dim_S_child_bearing, double);
  R_Free(internal->total_vaccine_doses);
  internal->total_vaccine_doses = (double*) R_Calloc(internal->dim_total_vaccine_doses, double);
  R_Free(internal->vaccination_attempts);
  internal->vaccination_attempts = (double*) R_Calloc(internal->dim_vaccination_attempts, double);
  R_Free(internal->vaccinations);
  internal->vaccinations = (double*) R_Calloc(internal->dim_vaccinations, double);
  R_Free(internal->vaccine_waning);
  internal->vaccine_waning = (double*) R_Calloc(internal->dim_vaccine_waning, double);
  internal->child_bearing_ages = (double*) user_get_array(user, false, internal->child_bearing_ages, "child_bearing_ages", NA_REAL, NA_REAL, 1, internal->dim_child_bearing_ages);
  internal->death_rate = (double*) user_get_array(user, false, internal->death_rate, "death_rate", NA_REAL, NA_REAL, 1, internal->dim_death_rate);
  internal->foi = (double*) user_get_array(user, false, internal->foi, "foi", NA_REAL, NA_REAL, 1, internal->dim_foi);
  for (int i = 1; i <= internal->dim_M; ++i) {
    internal->initial_M[i - 1] = internal->M_0[i - 1];
  }
  for (int i = 1; i <= internal->dim_V; ++i) {
    internal->initial_V[i - 1] = 0;
  }
  internal->offset_variable_M = internal->dim_R + internal->dim_S + internal->dim_V;
  internal->offset_variable_V = internal->dim_R + internal->dim_S;
  internal->R_0 = (double*) user_get_array(user, false, internal->R_0, "R_0", NA_REAL, NA_REAL, 1, internal->dim_R_0);
  internal->S_0 = (double*) user_get_array(user, false, internal->S_0, "S_0", NA_REAL, NA_REAL, 1, internal->dim_S_0);
  internal->vaccination_rate = (double*) user_get_array(user, false, internal->vaccination_rate, "vaccination_rate", NA_REAL, NA_REAL, 1, internal->dim_vaccination_rate);
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = internal->R_0[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->S_0[i - 1];
  }
  return R_NilValue;
}
SEXP deterministic_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP deterministic_use_dde_ptr) {
  return R_NilValue;
}
SEXP deterministic_metadata(SEXP internal_p) {
  deterministic_internal *internal = deterministic_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 4));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 4));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_V));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_M));
  SET_STRING_ELT(variable_names, 0, mkChar("S"));
  SET_STRING_ELT(variable_names, 1, mkChar("R"));
  SET_STRING_ELT(variable_names, 2, mkChar("V"));
  SET_STRING_ELT(variable_names, 3, mkChar("M"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SEXP output_length = PROTECT(allocVector(VECSXP, 1));
  SEXP output_names = PROTECT(allocVector(STRSXP, 1));
  setAttrib(output_length, R_NamesSymbol, output_names);
  SET_VECTOR_ELT(output_length, 0, ScalarInteger(internal->dim_vaccination_doses));
  SET_STRING_ELT(output_names, 0, mkChar("vaccination_doses"));
  SET_VECTOR_ELT(ret, 1, output_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(internal->dim_vaccination_doses));
  UNPROTECT(2);
  return ret;
}
SEXP deterministic_initial_conditions(SEXP internal_p, SEXP t_ptr) {
  deterministic_internal *internal = deterministic_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_M + internal->dim_R + internal->dim_S + internal->dim_V));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->dim_S, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_V, internal->initial_V, internal->dim_V * sizeof(double));
  memcpy(state + internal->offset_variable_M, internal->initial_M, internal->dim_M * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void deterministic_rhs(deterministic_internal* internal, double t, double * state, double * dstatedt, double * output) {
  double * S = state + 0;
  double * R = state + internal->dim_S;
  double * V = state + internal->offset_variable_V;
  double * M = state + internal->offset_variable_M;
  double loses_maternal = internal->maternal_waning * M[1];
  for (int i = 1; i <= internal->dim_ageing_M; ++i) {
    internal->ageing_M[i - 1] = internal->age_rate[i - 1] * M[i - 1];
  }
  for (int i = 1; i <= internal->dim_ageing_R; ++i) {
    internal->ageing_R[i - 1] = internal->age_rate[i - 1] * R[i - 1];
  }
  for (int i = 1; i <= internal->dim_ageing_S; ++i) {
    internal->ageing_S[i - 1] = internal->age_rate[i - 1] * S[i - 1];
  }
  for (int i = 1; i <= internal->dim_ageing_V; ++i) {
    internal->ageing_V[i - 1] = internal->age_rate[i - 1] * V[i - 1];
  }
  for (int i = 1; i <= internal->dim_deaths_M; ++i) {
    internal->deaths_M[i - 1] = internal->death_rate[i - 1] * M[i - 1];
  }
  for (int i = 1; i <= internal->dim_deaths_R; ++i) {
    internal->deaths_R[i - 1] = internal->death_rate[i - 1] * R[i - 1];
  }
  for (int i = 1; i <= internal->dim_deaths_S; ++i) {
    internal->deaths_S[i - 1] = internal->death_rate[i - 1] * S[i - 1];
  }
  for (int i = 1; i <= internal->dim_deaths_V; ++i) {
    internal->deaths_V[i - 1] = internal->death_rate[i - 1] * V[i - 1];
  }
  for (int i = 1; i <= internal->dim_infections; ++i) {
    internal->infections[i - 1] = internal->foi[i - 1] * S[i - 1];
  }
  for (int i = 1; i <= internal->dim_M_child_bearing; ++i) {
    internal->M_child_bearing[i - 1] = (R[i - 1] + V[i - 1]) * internal->child_bearing_ages[i - 1];
  }
  double maternal_vaccination_attempts = internal->vaccination_rate[1] * M[1];
  for (int i = 1; i <= internal->dim_natural_waning; ++i) {
    internal->natural_waning[i - 1] = internal->waning * R[i - 1];
  }
  for (int i = 1; i <= internal->dim_S_child_bearing; ++i) {
    internal->S_child_bearing[i - 1] = S[i - 1] * internal->child_bearing_ages[i - 1];
  }
  for (int i = 1; i <= internal->dim_vaccination_attempts; ++i) {
    internal->vaccination_attempts[i - 1] = internal->vaccination_rate[i - 1] * S[i - 1];
  }
  for (int i = 1; i <= internal->dim_vaccine_waning; ++i) {
    internal->vaccine_waning[i - 1] = internal->waning * V[i - 1];
  }
  double births_M = internal->birth_rate * odin_sum1(internal->M_child_bearing, 0, internal->dim_M_child_bearing);
  double births_S = internal->birth_rate * odin_sum1(internal->S_child_bearing, 0, internal->dim_S_child_bearing);
  {
     int i = 1;
     dstatedt[internal->dim_S + i - 1] = internal->infections[i - 1] - internal->ageing_R[i - 1] - internal->deaths_R[i - 1] - internal->natural_waning[i - 1];
  }
  for (int i = 2; i <= internal->n_age; ++i) {
    dstatedt[internal->dim_S + i - 1] = internal->infections[i - 1] + internal->ageing_R[i - 1 - 1] - internal->ageing_R[i - 1] - internal->deaths_R[i - 1] - internal->natural_waning[i - 1];
  }
  double maternal_vaccinations = maternal_vaccination_attempts * internal->vaccine_efficacy;
  for (int i = 1; i <= internal->dim_vaccinations; ++i) {
    internal->vaccinations[i - 1] = internal->vaccination_attempts[i - 1] * internal->vaccine_efficacy;
  }
  {
     int i = 1;
     dstatedt[internal->offset_variable_M + i - 1] = births_M + internal->vaccine_waning[0] - internal->ageing_M[0] - internal->deaths_M[0];
  }
  {
     int i = 2;
     dstatedt[internal->offset_variable_M + i - 1] = internal->ageing_M[0] + maternal_vaccinations - internal->ageing_M[1] - internal->deaths_M[1] - loses_maternal;
  }
  {
     int i = 1;
     dstatedt[0 + i - 1] = births_S + internal->natural_waning[i - 1] - internal->ageing_S[i - 1] - internal->infections[i - 1] - internal->deaths_S[i - 1];
  }
  {
     int i = 2;
     dstatedt[0 + i - 1] = loses_maternal + internal->ageing_S[i - 1 - 1] + internal->natural_waning[i - 1] + internal->vaccine_waning[i - 1] - internal->ageing_S[i - 1] - internal->infections[i - 1] - internal->deaths_S[i - 1];
  }
  for (int i = 3; i <= internal->n_age; ++i) {
    dstatedt[0 + i - 1] = internal->ageing_S[i - 1 - 1] + internal->natural_waning[i - 1] + internal->vaccine_waning[i - 1] - internal->ageing_S[i - 1] - internal->infections[i - 1] - internal->deaths_S[i - 1];
  }
  {
     int i = 1;
     dstatedt[internal->offset_variable_V + i - 1] = 0;
  }
  {
     int i = 2;
     dstatedt[internal->offset_variable_V + i - 1] = internal->vaccinations[i - 1] + maternal_vaccinations - internal->ageing_V[i - 1] - internal->deaths_V[i - 1] - internal->vaccine_waning[i - 1];
  }
  for (int i = 3; i <= internal->n_age; ++i) {
    dstatedt[internal->offset_variable_V + i - 1] = internal->vaccinations[i - 1] - internal->ageing_V[i - 1] - internal->deaths_V[i - 1] - internal->vaccine_waning[i - 1];
  }
  if (output) {
    {
       int i = 1;
       internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[0];
    }
    {
       int i = 2;
       internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[1] + maternal_vaccination_attempts;
    }
    for (int i = 3; i <= internal->n_age; ++i) {
      internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[i - 1];
    }
    for (int i = 1; i <= internal->dim_vaccination_doses; ++i) {
      output[0 + i - 1] = internal->total_vaccine_doses[i - 1];
    }
  }
}
void deterministic_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal) {
  deterministic_rhs((deterministic_internal*)internal, t, state, dstatedt, NULL);
}
void deterministic_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np) {
  deterministic_rhs(deterministic_internal_ds, *t, state, dstatedt, output);
}
void deterministic_output_dde(size_t n_eq, double t, double * state, size_t n_output, double * output, void * internal_p) {
  deterministic_internal *internal = (deterministic_internal*) internal_p;
  double * S = state + 0;
  double * M = state + internal->offset_variable_M;
  double maternal_vaccination_attempts = internal->vaccination_rate[1] * M[1];
  for (int i = 1; i <= internal->dim_vaccination_attempts; ++i) {
    internal->vaccination_attempts[i - 1] = internal->vaccination_rate[i - 1] * S[i - 1];
  }
  {
     int i = 1;
     internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[0];
  }
  {
     int i = 2;
     internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[1] + maternal_vaccination_attempts;
  }
  for (int i = 3; i <= internal->n_age; ++i) {
    internal->total_vaccine_doses[i - 1] = internal->vaccination_attempts[i - 1];
  }
  for (int i = 1; i <= internal->dim_vaccination_doses; ++i) {
    output[0 + i - 1] = internal->total_vaccine_doses[i - 1];
  }
}
SEXP deterministic_rhs_r(SEXP internal_p, SEXP t, SEXP state) {
  SEXP dstatedt = PROTECT(allocVector(REALSXP, LENGTH(state)));
  deterministic_internal *internal = deterministic_get_internal(internal_p, 1);
  SEXP output_ptr = PROTECT(allocVector(REALSXP, internal->dim_vaccination_doses));
  setAttrib(dstatedt, install("output"), output_ptr);
  UNPROTECT(1);
  double *output = REAL(output_ptr);
  deterministic_rhs(internal, scalar_real(t, "t"), REAL(state), REAL(dstatedt), output);
  UNPROTECT(1);
  return dstatedt;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%d'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for '%s'", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
                 i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for '%s'", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
double scalar_real(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  double ret = 0.0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    ret = REAL(x)[0];
  } else {
    Rf_error("Expected a numeric value for '%s'", name);
  }
  return ret;
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
