## Automatically generated by odin 1.5.4 - do not edit
deterministic_gz_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "deterministic_gz_rhs_dde",
      rhs_desolve = "deterministic_gz_rhs_desolve",
      initmod_desolve = "deterministic_gz_initmod_desolve",
      output_dde = "deterministic_gz_output_dde"),
    dll = "IVODE",
    user = c("age_rate", "child_bearing", "crude_birth_rate",
             "crude_death_rate", "crude_foi", "M_0", "n_age", "n_maternal",
             "prop_death", "R_0", "S_0", "tt_crude_birth_rate",
             "tt_crude_death_rate", "tt_crude_foi",
             "tt_vaccination_coverage", "vaccination_coverage",
             "vaccination_partial_coverage", "waning"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("deterministic_gz_rhs_dde", package = "IVODE")
        .C("deterministic_gz_rhs_desolve", package = "IVODE")
        .C("deterministic_gz_initmod_desolve", package = "IVODE")
        .C("deterministic_gz_output_dde", package = "IVODE")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("deterministic_gz_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "IVODE")
    },

    update_metadata = function() {
      meta <- .Call("deterministic_gz_metadata", private$ptr,
                    PACKAGE = "IVODE")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("deterministic_gz_create", user, PACKAGE = "IVODE")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/deterministic_gz.json", mustWork = TRUE,
                             package = "IVODE")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("deterministic_gz_set_user", private$ptr, user, PACKAGE = "IVODE")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("deterministic_gz_initial_conditions", private$ptr, t, PACKAGE = "IVODE")
    },

    rhs = function(t, y) {
      .Call("deterministic_gz_rhs_r", private$ptr, t, y, PACKAGE = "IVODE")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("deterministic_gz_contents", private$ptr, PACKAGE = "IVODE")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


deterministic_gz <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("deterministic_gz")
  deterministic_gz_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(deterministic_gz) <- "odin_generator"
attr(deterministic_gz, "generator") <- deterministic_gz_
deterministic_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "deterministic_rhs_dde",
      rhs_desolve = "deterministic_rhs_desolve",
      initmod_desolve = "deterministic_initmod_desolve",
      output_dde = "deterministic_output_dde"),
    dll = "IVODE",
    user = c("age_rate", "birth_rate", "death_rate", "foi", "M_0",
             "maternal_waning", "n_age", "R_0", "S_0", "tt_birth_rate",
             "tt_death_rate", "tt_foi", "tt_vaccine_doses", "vaccine_doses",
             "vaccine_efficacy", "vaccine_efficacy_disease", "waning"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("deterministic_rhs_dde", package = "IVODE")
        .C("deterministic_rhs_desolve", package = "IVODE")
        .C("deterministic_initmod_desolve", package = "IVODE")
        .C("deterministic_output_dde", package = "IVODE")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("deterministic_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "IVODE")
    },

    update_metadata = function() {
      meta <- .Call("deterministic_metadata", private$ptr,
                    PACKAGE = "IVODE")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("deterministic_create", user, PACKAGE = "IVODE")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/deterministic.json", mustWork = TRUE,
                             package = "IVODE")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("deterministic_set_user", private$ptr, user, PACKAGE = "IVODE")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("deterministic_initial_conditions", private$ptr, t, PACKAGE = "IVODE")
    },

    rhs = function(t, y) {
      .Call("deterministic_rhs_r", private$ptr, t, y, PACKAGE = "IVODE")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("deterministic_contents", private$ptr, PACKAGE = "IVODE")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


deterministic <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("deterministic")
  deterministic_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(deterministic) <- "odin_generator"
attr(deterministic, "generator") <- deterministic_
